### ISSUE TITLE
Newest version not working on heroku

### ISSUE THREAD

**Issue by Kurbm** [kirillplatonov/shopify-hotwire-sample#52]
Hey.

not sure if anyone else is able to deploy the newest version of this template to Heroku and get it running.

I have even tried to just deploy the basic version, but the app crashes as soon as you try to open it.

Here are the logs:

2022-11-24T01:22:40.140014+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:341:in `instance_exec'
2022-11-24T01:22:40.140015+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:341:in `resolve_source'
2022-11-24T01:22:40.140015+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `block in build_directive'
2022-11-24T01:22:40.140016+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `map'
2022-11-24T01:22:40.140016+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `build_directive'
2022-11-24T01:22:40.140016+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:317:in `block in build_directives'
2022-11-24T01:22:40.140017+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:312:in `each'
2022-11-24T01:22:40.140017+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:312:in `map'
2022-11-24T01:22:40.140017+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:312:in `build_directives'
2022-11-24T01:22:40.140018+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:288:in `build'
2022-11-24T01:22:40.140018+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:44:in `call'
2022-11-24T01:22:40.140018+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
2022-11-24T01:22:40.140019+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
2022-11-24T01:22:40.140020+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
2022-11-24T01:22:40.140020+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-11-24T01:22:40.140020+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
2022-11-24T01:22:40.140020+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
2022-11-24T01:22:40.140020+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
2022-11-24T01:22:40.140020+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
2022-11-24T01:22:40.140025+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2022-11-24T01:22:40.140025+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] rack (2.2.4) lib/rack/method_override.rb:24:in `call'
2022-11-24T01:22:40.140025+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] shopify_app (21.2.0) lib/shopify_app/middleware/jwt_middleware.rb:24:in `call_next'
2022-11-24T01:22:40.140025+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] shopify_app (21.2.0) lib/shopify_app/middleware/jwt_middleware.rb:12:in `call'
2022-11-24T01:22:40.140025+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] rack (2.2.4) lib/rack/runtime.rb:22:in `call'
2022-11-24T01:22:40.140026+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
2022-11-24T01:22:40.140026+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
2022-11-24T01:22:40.140026+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
2022-11-24T01:22:40.140026+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
2022-11-24T01:22:40.140026+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] railties (7.0.4) lib/rails/engine.rb:530:in `call'
2022-11-24T01:22:40.140027+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] puma (5.6.5) lib/puma/configuration.rb:252:in `call'
2022-11-24T01:22:40.140027+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
2022-11-24T01:22:40.140027+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2022-11-24T01:22:40.140027+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
2022-11-24T01:22:40.140027+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] puma (5.6.5) lib/puma/server.rb:443:in `process_client'
2022-11-24T01:22:40.140027+00:00 app[web.1]: [17872031-3377-4f24-8b17-80ff72655005] puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
2022-11-24T01:22:40.141257+00:00 heroku[router]: at=info method=GET path="/?embedded=1&hmac=1efcbe9cab84c7ddf38afb33d6e2e1a7107e3f1cecb18ed9a3592b0f9566c972&host=dXJiYXVtLXRlc3Qtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg&locale=en-DE&session=ebe5b69f863c5f6a9e531261bcef8e9f09281dac4994549b4d2bcfd6b4a20fc9&shop=urbaum-test-store.myshopify.com&timestamp=1669252959" host=shopify-hotwire-test.herokuapp.com request_id=17872031-3377-4f24-8b17-80ff72655005 fwd="79.208.53.32" dyno=web.1 connect=0ms service=9ms status=500 bytes=1827 protocol=https
2022-11-24T01:22:40.910839+00:00 app[web.1]: I, [2022-11-24T01:22:40.910767 #4]  INFO -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb] Started GET "/?embedded=1&hmac=861a7c7ee26d215e7d5b31cd7c7817ad0a99608ced40e278810c4d75108a1d30&host=dXJiYXVtLXRlc3Qtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg&locale=en-DE&session=ebe5b69f863c5f6a9e531261bcef8e9f09281dac4994549b4d2bcfd6b4a20fc9&shop=urbaum-test-store.myshopify.com&timestamp=1669252960" for 79.208.53.32 at 2022-11-24 01:22:40 +0000
2022-11-24T01:22:40.911626+00:00 app[web.1]: I, [2022-11-24T01:22:40.911553 #4]  INFO -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb] Processing by SplashPageController#index as HTML
2022-11-24T01:22:40.911631+00:00 app[web.1]: I, [2022-11-24T01:22:40.911611 #4]  INFO -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb]   Parameters: {"embedded"=>"1", "hmac"=>"861a7c7ee26d215e7d5b31cd7c7817ad0a99608ced40e278810c4d75108a1d30", "host"=>"dXJiYXVtLXRlc3Qtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg", "locale"=>"en-DE", "session"=>"ebe5b69f863c5f6a9e531261bcef8e9f09281dac4994549b4d2bcfd6b4a20fc9", "shop"=>"urbaum-test-store.myshopify.com", "timestamp"=>"1669252960"}
2022-11-24T01:22:40.914299+00:00 app[web.1]: I, [2022-11-24T01:22:40.914238 #4]  INFO -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb] Redirected to https://shopify-hotwire-test.herokuapp.com/login?shop=urbaum-test-store.myshopify.com&host=dXJiYXVtLXRlc3Qtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg&return_to=%2F%3Fembedded%3D1%26hmac%3D861a7c7ee26d215e7d5b31cd7c7817ad0a99608ced40e278810c4d75108a1d30%26host%3DdXJiYXVtLXRlc3Qtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg%26locale%3Den-DE%26session%3Debe5b69f863c5f6a9e531261bcef8e9f09281dac4994549b4d2bcfd6b4a20fc9%26shop%3Durbaum-test-store.myshopify.com%26timestamp%3D1669252960
2022-11-24T01:22:40.914452+00:00 app[web.1]: I, [2022-11-24T01:22:40.914400 #4]  INFO -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb] Filter chain halted as :check_shop_known rendered or redirected
2022-11-24T01:22:40.914648+00:00 app[web.1]: I, [2022-11-24T01:22:40.914593 #4]  INFO -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb] Completed 302 Found in 3ms (ActiveRecord: 0.8ms | Allocations: 330)
2022-11-24T01:22:40.915453+00:00 heroku[router]: at=info method=GET path="/?embedded=1&hmac=861a7c7ee26d215e7d5b31cd7c7817ad0a99608ced40e278810c4d75108a1d30&host=dXJiYXVtLXRlc3Qtc3RvcmUubXlzaG9waWZ5LmNvbS9hZG1pbg&locale=en-DE&session=ebe5b69f863c5f6a9e531261bcef8e9f09281dac4994549b4d2bcfd6b4a20fc9&shop=urbaum-test-store.myshopify.com&timestamp=1669252960" host=shopify-hotwire-test.herokuapp.com request_id=14b0aac7-91b9-4461-b593-6b7d9db8afbb fwd="79.208.53.32" dyno=web.1 connect=0ms service=7ms status=500 bytes=1827 protocol=https
2022-11-24T01:22:40.915843+00:00 app[web.1]: F, [2022-11-24T01:22:40.915782 #4] FATAL -- : [14b0aac7-91b9-4461-b593-6b7d9db8afbb]
2022-11-24T01:22:40.915846+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] TypeError (Passed `nil` into T.must):
2022-11-24T01:22:40.915847+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb]
2022-11-24T01:22:40.915847+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] sorbet-runtime (0.5.10554) lib/types/_types.rb:218:in `must'
2022-11-24T01:22:40.915847+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] shopify_api (12.2.1) lib/shopify_api/context.rb:157:in `host_scheme'
2022-11-24T01:22:40.915848+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] sorbet-runtime (0.5.10554) lib/types/private/methods/call_validation_2_7.rb:57:in `bind_call'
2022-11-24T01:22:40.915849+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] sorbet-runtime (0.5.10554) lib/types/private/methods/call_validation_2_7.rb:57:in `block in create_validator_method_fast0'
2022-11-24T01:22:40.915849+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] shopify_app (21.2.0) lib/shopify_app/controller_concerns/frame_ancestors.rb:11:in `block (3 levels) in <module:FrameAncestors>'
2022-11-24T01:22:40.915850+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:341:in `instance_exec'
2022-11-24T01:22:40.915850+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:341:in `resolve_source'
2022-11-24T01:22:40.915851+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `block in build_directive'
2022-11-24T01:22:40.915851+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `map'
2022-11-24T01:22:40.915852+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `build_directive'
2022-11-24T01:22:40.915852+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:317:in `block in build_directives'
2022-11-24T01:22:40.915852+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:312:in `each'
2022-11-24T01:22:40.915853+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:312:in `map'
2022-11-24T01:22:40.915853+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:312:in `build_directives'
2022-11-24T01:22:40.915853+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:288:in `build'
2022-11-24T01:22:40.915853+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:44:in `call'
2022-11-24T01:22:40.915854+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
2022-11-24T01:22:40.915854+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
2022-11-24T01:22:40.915854+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
2022-11-24T01:22:40.915854+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2022-11-24T01:22:40.915854+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
2022-11-24T01:22:40.915855+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2022-11-24T01:22:40.915855+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
2022-11-24T01:22:40.915855+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
2022-11-24T01:22:40.915855+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
2022-11-24T01:22:40.915856+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
2022-11-24T01:22:40.915856+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-11-24T01:22:40.915856+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
2022-11-24T01:22:40.915857+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
2022-11-24T01:22:40.915857+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
2022-11-24T01:22:40.915857+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
2022-11-24T01:22:40.915862+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2022-11-24T01:22:40.915863+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] rack (2.2.4) lib/rack/method_override.rb:24:in `call'
2022-11-24T01:22:40.915863+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] shopify_app (21.2.0) lib/shopify_app/middleware/jwt_middleware.rb:24:in `call_next'
2022-11-24T01:22:40.915864+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] shopify_app (21.2.0) lib/shopify_app/middleware/jwt_middleware.rb:12:in `call'
2022-11-24T01:22:40.915864+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] rack (2.2.4) lib/rack/runtime.rb:22:in `call'
2022-11-24T01:22:40.915864+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
2022-11-24T01:22:40.915865+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
2022-11-24T01:22:40.915865+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
2022-11-24T01:22:40.915865+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
2022-11-24T01:22:40.915866+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] railties (7.0.4) lib/rails/engine.rb:530:in `call'
2022-11-24T01:22:40.915866+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] puma (5.6.5) lib/puma/configuration.rb:252:in `call'
2022-11-24T01:22:40.915866+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
2022-11-24T01:22:40.915867+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2022-11-24T01:22:40.915867+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
2022-11-24T01:22:40.915868+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] puma (5.6.5) lib/puma/server.rb:443:in `process_client'
2022-11-24T01:22:40.915868+00:00 app[web.1]: [14b0aac7-91b9-4461-b593-6b7d9db8afbb] puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

If anyone else got it running, please let me know, how you did it.

Thanks and best,
Kevin

**Comment by Kurbm** [comment]
Nevermind, just found my issue.

You need to add the host in the config vars in heroku.

@kirillplatonov maybe interesting to add in the readme as well, for people like me :)

**Comment by kirillplatonov** [comment]
@Kurbm feel free to open a PR 😉
